version: "3.7"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  httpd:
    image: httpd
    volumes:
      - './cons-config:/usr/local/apache2/htdocs/cons-config:ro'
    ports:
      - "80:80"
